language: java
jdk:
  - openjdk7

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EWbOUn3lprcV7OiWMQLDUfR2kDyDHCvzPpUDNvoLG0YgdLpjymXgUGRuVdbiBdeiKER56WbkiZuNpqMyFoRQHozjjTvCHYrIofkwZJFK89GvvhxKKbkjS0XFS/3SiNytquhavF9TePX5CMqVb8KMqNVWzUtsTcFfhrgqni4QL2o="

addons:
  coverity_scan:
    project:
      name: "plt-tud/r43ples"
      description: "Revision Control for the Semantic Web"
    notification_email: markus.graube@tu-dresden.de
    build_command_prepend:
    build_command: ant
    branch_pattern: coverity_scan

before_install:
  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main"
  - sudo apt-get update -qq
  - sudo apt-get install -qq virtuoso-opensource
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/virtuoso-opensource_6.1.6%2Brepack-0ubuntu3_all.deb
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/virtuoso-opensource-6.1_6.1.6%2Brepack-0ubuntu3_amd64.deb
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/virtuoso-opensource-6.1-bin_6.1.6%2Brepack-0ubuntu3_amd64.deb
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/virtuoso-opensource-6.1-common_6.1.6%2Brepack-0ubuntu3_amd64.deb
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/libvirtuoso5.5-cil_6.1.6%2Brepack-0ubuntu3_amd64.deb
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/libvirtodbc0_6.1.6%2Brepack-0ubuntu3_amd64.deb
  - #wget http://launchpadlibrarian.net/168544103/libmagickwand5_6.7.7.10-6ubuntu3_amd64.deb
  - #wget https://launchpad.net/ubuntu/+archive/primary/+files/virtuoso-minimal_6.1.6%2Brepack-0ubuntu3_all.deb
  - echo `virtuoso-t -h`
  - echo "RUN=yes" | sudo tee -a /etc/default/virtuoso-opensource-6.1
  - sudo /etc/init.d/virtuoso-opensource-6.1 start
