language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EWbOUn3lprcV7OiWMQLDUfR2kDyDHCvzPpUDNvoLG0YgdLpjymXgUGRuVdbiBdeiKER56WbkiZuNpqMyFoRQHozjjTvCHYrIofkwZJFK89GvvhxKKbkjS0XFS/3SiNytquhavF9TePX5CMqVb8KMqNVWzUtsTcFfhrgqni4QL2o="

addons:
  coverity_scan:
    project:
      name: "plt-tud/r43ples"
      description: "Revision Control for the Semantic Web"
    notification_email: markus.graube@tu-dresden.de
    build_command_prepend:
    build_command:
    branch_pattern: coverity_scan

before_install:
- sudo apt-get install -qq virtuoso-opensource
- echo "RUN=yes" | sudo tee -a /etc/default/virtuoso-opensource-6.1
- sudo /etc/init.d/virtuoso-opensource-6.1 start
