language: java
jdk:
  - openjdk7

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "EWbOUn3lprcV7OiWMQLDUfR2kDyDHCvzPpUDNvoLG0YgdLpjymXgUGRuVdbiBdeiKER56WbkiZuNpqMyFoRQHozjjTvCHYrIofkwZJFK89GvvhxKKbkjS0XFS/3SiNytquhavF9TePX5CMqVb8KMqNVWzUtsTcFfhrgqni4QL2o="
   - secure: "WHUbL9LOlJo5a/6TewBV7BZgfpUzDnEur0uI3n5KxmbxGPnlSUYyLoaRFF83Ukys3Mb0xjdleLrOCk+EA7VFMtsxADroHGmK5tSPJD/GGWUo+jdmk1/cETKlgpPvOFKG5Ui19ydqMexACMGnzcy9XoyYwOMyIO/ZbrVjdrq3VtI="


addons:
  coverity_scan:
    project:
      name: "plt-tud/r43ples"
      description: "Revision Control for the Semantic Web"
    notification_email: markus.graube@tu-dresden.de
    build_command_prepend:
    build_command: ant
    branch_pattern: coverity_scan

before_install:
    - #sudo apt-add-repository -y ppa:kubuntu-ppa/backports
    - #sudo apt-get update -qq
    - #sudo apt-get install -qq virtuoso-opensource
    - #echo "RUN=yes" | sudo tee -a /etc/default/virtuoso-opensource-6.1
    - #sudo /etc/init.d/virtuoso-opensource-6.1 start
    - #sudo apt-get install -qq dpkg-dev build-essential autoconf automake libtool flex bison gperf gawk m4 make odbcinst libxml2-dev libssl-dev libreadline-dev
    - #git clone https://github.com/openlink/virtuoso-opensource.git
    - #cd virtuoso-opensource
    - #export CFLAGS="-O2 -m64"
    - #./autogen.sh
    - #./configure
    - #make
    - #sudo make install
    - # doesn't start
    - # sudo /etc/init.d/virtuoso-opensource start
    - # use LOD2 stack virtuoso 7 package
    - sudo apt-get update -qq
    - sudo apt-get install -qq libc6 ibldap-2.4-2 libreadline6 libssl1.0.0
    - wget https://cloudstore.zih.tu-dresden.de/public.php?service=files&t=27bfa7d71ed6b9d3e3225da318cc4639 
    - sudo dpkg -i public.php?service=files&t=27bfa7d71ed6b9d3e3225da318cc4639
    - sudo /etc/init.d/virtuoso-opensource start

  
after_success:
    - ./.coverity.sh
