language: java
jdk:
  - openjdk7

env:
  global:
    # Global variables encypted via "travis encryt"  using the project repo's public key
    # encrypted COVERITY_SCAN_TOKEN
    -  secure: "ed4oH5JO8IPEy12khiyQWajKv0NKwMqn2mOv7xxeJvlIWL06xVuW+j9OLcDQh5nMF06ZbcOuH/ctiwj5uweGPhyK4Sc59pd3k8L5FsnFzzvXddKHaLe+KagHMLDazCXcnf8H74mQyv5lkUkI9saUwhLZv6F+rn6tnayp6D++UKo="
    # encrypted GITHUB_AUTH_TOKEN
    - secure: "WHUbL9LOlJo5a/6TewBV7BZgfpUzDnEur0uI3n5KxmbxGPnlSUYyLoaRFF83Ukys3Mb0xjdleLrOCk+EA7VFMtsxADroHGmK5tSPJD/GGWUo+jdmk1/cETKlgpPvOFKG5Ui19ydqMexACMGnzcy9XoyYwOMyIO/ZbrVjdrq3VtI="


addons:
  coverity_scan:
    project:
      name: plt-tud/r43ples
      description: Revision Control for the Semantic Web
    notification_email: markus.graube@tu-dresden.de
    build_command_prepend:
    build_command: ant
    branch_pattern: coverity_scan

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libc6 ibldap-2.4-2 libreadline6 libssl1.0.0
    - wget http://wwwpub.zih.tu-dresden.de/~mgraube/virtuoso-opensource_7.1_amd64.deb
    - sudo dpkg -i virtuoso-opensource_7.1_amd64.deb

  
after_success:
    - ./.coverity.sh
    - ./.update-gh-pages.sh
